name: Organisation Metrics
on:
  schedule: [{cron: "0 3 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Configure Git to use token
        run: |
          git config --global url."https://${{ secrets.METRICS_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - uses: lowlighter/metrics@v3.34
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
        with:
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage, lines
          plugin_languages_limit: 8
          plugin_languages_colors: rainbow
          plugin_languages_analysis_timeout: 60
          commits_authoring: Daniel Winning, DanielWinning, daniel@winningsoftware.co.uk
          token: ${{ secrets.METRICS_TOKEN }}
          user: WinningSoftwareDev
          base: header, repositories
          base_indepth: yes
          plugin_lines: yes
          config_timezone: Europe/London
          filename: profile/github-metrics.svg
          repositories_batch: 100
          repositories_affiliations: owner, collaborator, organization_member
          retries: 3
          retries_delay: 60
          debug: yes