name: Organisation Metrics
on:
  schedule: [{cron: "0 3 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: WinningSoftwareDev
          template: classic
          base: header, repositories, languages
          config_timezone: Europe/London
          filename: profile/github-metrics.svg
          repositories_batch: 5
          repositories_affiliations: owner
          retries: 3
          retries_delay: 60