name: Organisation Metrics
on:
  schedule: [{cron: "0 3 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          commits_authoring: Daniel Winning, DanielWinning, daniel@winningsoftware.co.uk
          token: ${{ secrets.METRICS_TOKEN }}
          user: WinningSoftwareDev
          base: header
          plugin_lines: yes
          config_timezone: Europe/London
          filename: profile/github-metrics.svg
          repositories_batch: 10
          repositories_affiliations: owner
          retries: 3
          retries_delay: 60