name: Test Access Token
on:
  workflow_dispatch:
jobs:
  test-access:
    runs-on: ubuntu-latest
    steps:
      - name: Test token access
        run: |
          git clone https://${{ secrets.METRICS_TOKEN }}@github.com/WinningSoftwareDev/sharp-notes.git
